### ISSUE TITLE
Crash when breaking Thermal Expansion Tank

### ISSUE THREAD

**Issue by RhinoKneel** [TominoCZ/FancyBlockParticles#1]
Had brought this up with TeamCOFH as Thermal Expansion's 1.10.2 is still quite new, but KingLemming noted no issues and on further investigation, was found to be caused by Fancy Block Particles 2.0.2 [1.10.2]

Halfway through trying to manually break a Portable Tank caused a crash. I had noticed before too a lack of particle effects happening before the crash. Other machines added by the mod had no similar issues.

[crash-2017-03-07_18.12.39-client.txt](https://github.com/TominoCZ/FancyBlockParticles/files/826171/crash-2017-03-07_18.12.39-client.txt)

**Comment by TominoCZ** [comment]
I'm sorry.. I've been busy, now I can get back to work :)
Anyways...
That crash is really interesting. I'm not completely sure what it crashes on.
I am currently working on a complete rewrite and huge optimizations. I've realized how easily the particle spawning/replacing can be done. I was only making it worse :D

Hopefully the new update will resolve this problem :)

**Comment by TominoCZ** [comment]
I have finished recoding everything pretty much. I'll check everything tomorrow and release it asap.
