### ISSUE TITLE
Settings reset everytime Minecraft launches

### ISSUE THREAD

**Issue by Dekamir** [TominoCZ/FancyBlockParticles#100]
## Steps to reproduce issue:
Change settings
Launch Minecraft
File gets updated when Minecraft is launched to be reset.

## MC Version:
1.11.2
## FBP Version:
2.4.0
## Forge Version:
8.0.99.99

## Installed Mods
[dir.txt](https://github.com/TominoCZ/FancyBlockParticles/files/2267593/dir.txt)

**Comment by TominoCZ** [comment]
The next update should fix the issue.
