### ISSUE TITLE
FBP doesn't like Biomes O' Plenty!

### ISSUE THREAD

**Issue by Adahel** [TominoCZ/FancyBlockParticles#105]
## Steps to reproduce issue:
FPB + Biomes O' Plenty: apparently, but after much research, I came to the conclusion that the problem is in your mod.
## MC Version:
1.8.9
## FBP Version:
FBP-2.4.0
## Forge Version (e.g. 2604):
1.8.9-11.15.1.2318-1.8.9

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ShoulderPlugin (ShoulderSurfing-1.8.8_1.8.9-1.1.jar)
  DLFMLCorePlugin (DynamicLights-1.8.8.jar)
  BetterFoliageLoader (BetterFoliage-MC1.8.x-2.0.15.jar)
  dsurroundcore (DynamicSurroundings-1.8.9-2.0.5.6.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 29/09/18 21:27
Description: Exception while adding particle

java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class biomesoplenty.common.enums.BOPPlants, values=[shortgrass, mediumgrass, bush, sprout, poisonivy, berrybush, shrub, wheatgrass, dampgrass, koru, cloverpatch, leafpile, deadleafpile, deadgrass, desertgrass, desertsprouts]} as it does not exist in BlockState{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:137)
	at biomesoplenty.common.block.BlockBOPPlant.func_180662_a(BlockBOPPlant.java:307)
	at com.TominoCZ.FBP.particle.FBPParticleDigging.multiplyColor(FBPParticleDigging.java:188)
	at com.TominoCZ.FBP.particle.FBPParticleDigging.<init>(FBPParticleDigging.java:172)
	at com.TominoCZ.FBP.particle.FBPParticleManager.func_178927_a(FBPParticleManager.java:261)
	at net.minecraft.client.renderer.RenderGlobal.func_174974_b(RenderGlobal.java:2948)
	at net.minecraft.client.renderer.RenderGlobal.func_180442_a(RenderGlobal.java:2834)
	at net.minecraft.world.World.func_175720_a(World.java:1085)
	at net.minecraft.world.World.func_175688_a(World.java:1072)
	at net.minecraft.entity.Entity.func_174808_Z(Entity.java:995)
	at net.minecraft.entity.Entity.func_174830_Y(Entity.java:980)
	at net.minecraft.entity.Entity.func_70030_z(Entity.java:350)
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:189)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:279)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1564)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:283)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:117)
	at net.minecraft.world.World.func_72866_a(World.java:1862)
	at net.minecraft.world.World.func_72870_g(World.java:1831)
	at net.minecraft.world.World.func_72939_s(World.java:1663)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2089)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:137)
	at biomesoplenty.common.block.BlockBOPPlant.func_180662_a(BlockBOPPlant.java:307)
	at com.TominoCZ.FBP.particle.FBPParticleDigging.multiplyColor(FBPParticleDigging.java:188)
	at com.TominoCZ.FBP.particle.FBPParticleDigging.<init>(FBPParticleDigging.java:172)
	at com.TominoCZ.FBP.particle.FBPParticleManager.func_178927_a(FBPParticleManager.java:261)
	at net.minecraft.client.renderer.RenderGlobal.func_174974_b(RenderGlobal.java:2948)

-- Particle being added --
Details:
	ID: 37
	Parameters: [I@4e1d166
	Position: 180,03,74,10,-87,11 - World: (180,74,-88), Chunk: (at 4,4,8 in 11,-6; contains blocks 176,0,-96 to 191,255,-81), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
Stacktrace:
	at net.minecraft.client.renderer.RenderGlobal.func_180442_a(RenderGlobal.java:2834)
	at net.minecraft.world.World.func_175720_a(World.java:1085)
	at net.minecraft.world.World.func_175688_a(World.java:1072)
	at net.minecraft.entity.Entity.func_174808_Z(Entity.java:995)
	at net.minecraft.entity.Entity.func_174830_Y(Entity.java:980)
	at net.minecraft.entity.Entity.func_70030_z(Entity.java:350)
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:189)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:279)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1564)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:283)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:117)
	at net.minecraft.world.World.func_72866_a(World.java:1862)
	at net.minecraft.world.World.func_72870_g(World.java:1831)

-- Entity being ticked --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityPlayerSP)
	Entity ID: 56606
	Entity Name: Black_Spider_Man
	Entity's Exact location: 180,00, 74,00, -86,83
	Entity's Block location: 179,00,74,00,-87,00 - World: (179,74,-87), Chunk: (at 3,4,9 in 11,-6; contains blocks 176,0,-96 to 191,255,-81), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: -0,03, -0,08, 0,13
	Entity's Rider: ~~ERROR~~ NullPointerException: null
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1663)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Black_Spider_Man'/56606, l='MpServer', x=180,00, y=74,00, z=-86,83]]
	Chunk stats: MultiplayerChunkCache: 1073, 1073
	Level seed: 0
	Level generator: ID 06 - OWG, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: 166,00,65,00,-57,00 - World: (166,65,-57), Chunk: (at 6,4,7 in 10,-4; contains blocks 160,0,-64 to 175,255,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 31127 game time, 31127 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 100 total; [EntitySpider['Spider'/277510, l='MpServer', x=243,28, y=13,00, z=-157,94], EntityBat['Bat'/280599, l='MpServer', x=142,99, y=44,50, z=-98,92], EntityBat['Bat'/280604, l='MpServer', x=143,69, y=44,33, z=-99,41], EntityBat['Bat'/280601, l='MpServer', x=149,51, y=37,69, z=-87,44], EntityCreeper['Creeper'/279584, l='MpServer', x=112,50, y=18,00, z=-90,50], EntityCreeper['Creeper'/279586, l='MpServer', x=112,50, y=18,00, z=-87,50], EntitySpider['Spider'/278612, l='MpServer', x=237,69, y=15,00, z=-131,59], EntityBat['Bat'/278625, l='MpServer', x=177,25, y=37,10, z=-83,25], EntityBat['Bat'/280692, l='MpServer', x=249,95, y=17,18, z=-120,39], EntityZombie['Zombie'/279667, l='MpServer', x=139,50, y=44,00, z=-141,50], EntitySkeleton['Skeleton'/269452, l='MpServer', x=248,50, y=21,00, z=-105,50], EntitySheep['Sheep'/56479, l='MpServer', x=140,84, y=71,00, z=-103,88], EntitySheep['Sheep'/56480, l='MpServer', x=106,91, y=74,00, z=-25,13], EntitySheep['Sheep'/56481, l='MpServer', x=141,13, y=66,00, z=-59,34], EntitySheep['Sheep'/56482, l='MpServer', x=136,41, y=73,00, z=-94,34], EntitySheep['Sheep'/56495, l='MpServer', x=151,91, y=69,00, z=-101,94], EntitySheep['Sheep'/56496, l='MpServer', x=187,03, y=79,00, z=-108,88], EntitySheep['Sheep'/56497, l='MpServer', x=172,53, y=64,00, z=-81,22], EntitySheep['Sheep'/56498, l='MpServer', x=206,41, y=72,00, z=-78,66], EntitySheep['Sheep'/56499, l='MpServer', x=120,81, y=71,00, z=-59,44], EntitySheep['Sheep'/56500, l='MpServer', x=182,44, y=72,00, z=-83,53], EntitySheep['Sheep'/56501, l='MpServer', x=173,09, y=68,00, z=-70,97], EntitySheep['Sheep'/56502, l='MpServer', x=149,66, y=68,00, z=-101,84], EntityPig['Pig'/56510, l='MpServer', x=211,50, y=73,00, z=-138,50], EntityPig['Pig'/56511, l='MpServer', x=211,50, y=73,00, z=-138,50], EntityPig['Pig'/56512, l='MpServer', x=209,50, y=73,00, z=-137,50], EntityPig['Pig'/56513, l='MpServer', x=213,50, y=73,00, z=-139,50], EntityPig['Pig'/56514, l='MpServer', x=214,50, y=68,00, z=-29,50], EntityPig['Pig'/56515, l='MpServer', x=215,50, y=69,00, z=-31,50], EntityPig['Pig'/56516, l='MpServer', x=206,06, y=64,00, z=-19,25], EntityPig['Pig'/56517, l='MpServer', x=211,50, y=67,00, z=-25,56], EntitySheep['Sheep'/56518, l='MpServer', x=215,75, y=67,00, z=-25,56], EntitySheep['Sheep'/56519, l='MpServer', x=214,44, y=67,00, z=-25,56], EntitySheep['Sheep'/56520, l='MpServer', x=214,50, y=68,00, z=-27,50], EntitySheep['Sheep'/56521, l='MpServer', x=213,13, y=67,00, z=-24,16], EntityBat['Bat'/280790, l='MpServer', x=105,53, y=31,06, z=-102,38], EntityBat['Bat'/280791, l='MpServer', x=106,53, y=31,81, z=-106,56], EntityBat['Bat'/280798, l='MpServer', x=105,25, y=31,56, z=-105,34], EntityBat['Bat'/280793, l='MpServer', x=107,50, y=31,81, z=-111,50], EntityBat['Bat'/280794, l='MpServer', x=107,50, y=31,75, z=-105,31], EntityCreeper['Creeper'/277733, l='MpServer', x=106,50, y=31,00, z=-102,50], EntityZombie['Zombie'/279783, l='MpServer', x=222,84, y=14,00, z=-129,66], EntityCreeper['Creeper'/280808, l='MpServer', x=188,50, y=51,00, z=-16,50], EntityCreeper['Creeper'/280809, l='MpServer', x=188,31, y=53,00, z=-12,94], EntityItem['item.tile.sapling.spruce'/279805, l='MpServer', x=178,13, y=71,00, z=-82,34], EntityCreeper['Creeper'/274691, l='MpServer', x=166,50, y=18,00, z=-88,50], EntityCreeper['Creeper'/280848, l='MpServer', x=232,50, y=17,00, z=-135,50], EntityPlayerSP['Black_Spider_Man'/56606, l='MpServer', x=180,00, y=74,00, z=-86,83], EntitySquid['Squid'/279849, l='MpServer', x=151,69, y=62,72, z=-111,19], EntitySquid['Squid'/279850, l='MpServer', x=150,53, y=62,00, z=-110,59], EntitySquid['Squid'/279851, l='MpServer', x=150,63, y=62,25, z=-112,34], EntityEnderman['Enderman'/279856, l='MpServer', x=149,50, y=26,00, z=-113,50], EntitySkeleton['Skeleton'/280888, l='MpServer', x=128,50, y=29,00, z=-163,50], EntityCreeper['Creeper'/280889, l='MpServer', x=130,50, y=29,00, z=-163,50], EntityCreeper['Creeper'/280890, l='MpServer', x=129,50, y=29,00, z=-163,50], EntityCreeper['Creeper'/279888, l='MpServer', x=124,50, y=36,00, z=-106,50], EntityCreeper['Creeper'/280931, l='MpServer', x=240,50, y=15,00, z=-130,50], EntityCreeper['Creeper'/280936, l='MpServer', x=208,50, y=63,00, z=-148,50], EntityCreeper['Creeper'/280937, l='MpServer', x=205,50, y=63,00, z=-147,50], EntitySkeleton['Skeleton'/275829, l='MpServer', x=209,50, y=20,00, z=-103,50], EntityZombie['Zombie'/278916, l='MpServer', x=105,50, y=12,00, z=-76,50], EntityCreeper['Creeper'/256393, l='MpServer', x=194,50, y=22,00, z=-27,50], EntitySkeleton['Skeleton'/279997, l='MpServer', x=145,50, y=23,00, z=-107,50], EntitySkeleton['Skeleton'/279998, l='MpServer', x=147,50, y=23,00, z=-109,50], EntityBat['Bat'/278990, l='MpServer', x=180,25, y=35,10, z=-87,63], EntitySkeleton['Skeleton'/281033, l='MpServer', x=203,50, y=23,00, z=-51,31], EntityCreeper['Creeper'/281034, l='MpServer', x=200,80, y=24,00, z=-51,41], EntitySkeleton['Skeleton'/280018, l='MpServer', x=216,50, y=19,00, z=-97,50], EntityCreeper['Creeper'/281101, l='MpServer', x=149,50, y=21,00, z=-98,50], EntityCreeper['Creeper'/281102, l='MpServer', x=148,56, y=21,23, z=-97,32], EntitySkeleton['Skeleton'/281103, l='MpServer', x=202,50, y=52,00, z=-164,50], EntityCreeper['Creeper'/280095, l='MpServer', x=136,50, y=38,00, z=-156,50], EntitySkeleton['Skeleton'/280090, l='MpServer', x=259,50, y=34,00, z=-164,50], EntitySkeleton['Skeleton'/280091, l='MpServer', x=260,50, y=34,00, z=-163,50], EntityItem['item.tile.sapling.spruce'/276020, l='MpServer', x=177,91, y=75,00, z=-80,81], EntitySkeleton['Skeleton'/280126, l='MpServer', x=130,50, y=36,00, z=-108,50], EntityCreeper['Creeper'/280198, l='MpServer', x=254,50, y=16,00, z=-140,50], EntityCreeper['Creeper'/280199, l='MpServer', x=253,50, y=16,00, z=-138,50], EntityCreeper['Creeper'/280192, l='MpServer', x=255,50, y=16,00, z=-162,50], EntitySkeleton['Skeleton'/280214, l='MpServer', x=154,50, y=30,00, z=-90,50], EntityCreeper['Creeper'/277139, l='MpServer', x=122,50, y=14,00, z=-70,50], EntityBat['Bat'/280244, l='MpServer', x=139,23, y=27,33, z=-97,04], EntityItem['item.tile.sapling.spruce'/277180, l='MpServer', x=177,88, y=75,00, z=-79,66], EntityCreeper['Creeper'/276188, l='MpServer', x=209,50, y=24,00, z=-62,50], EntityCreeper['Creeper'/276190, l='MpServer', x=205,44, y=21,00, z=-70,47], EntitySkeleton['Skeleton'/276200, l='MpServer', x=130,50, y=32,00, z=-154,50], EntitySkeleton['Skeleton'/273176, l='MpServer', x=144,13, y=45,00, z=-105,50], EntitySkeleton['Skeleton'/280355, l='MpServer', x=205,81, y=24,00, z=-62,59], EntityItem['item.tile.coral.algae'/280364, l='MpServer', x=137,13, y=60,00, z=-37,88], EntitySkeleton['Skeleton'/280396, l='MpServer', x=152,50, y=22,00, z=-101,50], EntitySkeleton['Skeleton'/280397, l='MpServer', x=152,50, y=22,00, z=-100,50], EntitySkeleton['Skeleton'/280395, l='MpServer', x=148,50, y=22,00, z=-100,50], EntitySquid['Squid'/277360, l='MpServer', x=144,91, y=63,47, z=-125,38], EntitySkeleton['Skeleton'/280466, l='MpServer', x=206,56, y=31,00, z=-8,16], EntityBat['Bat'/280499, l='MpServer', x=188,60, y=55,05, z=-9,41], EntityCreeper['Creeper'/278461, l='MpServer', x=119,28, y=63,00, z=-83,66], EntityZombie['Zombie'/278463, l='MpServer', x=118,28, y=63,00, z=-85,31], EntitySkeleton['Skeleton'/279487, l='MpServer', x=144,50, y=23,00, z=-102,50], EntityItem['item.tile.coral.algae'/246719, l='MpServer', x=137,34, y=61,00, z=-39,69], EntityBat['Bat'/280525, l='MpServer', x=248,94, y=21,58, z=-146,52]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:417)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	CPU: 8x Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
	Java Version: 1.8.0_172, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 734926016 bytes (700 MB) / 1569603584 bytes (1496 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 1
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_I7 20 mods loaded, 20 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJAAAAAAAAA	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJAAAAAAAAA	BetterFoliage{2.0.15} [Better Foliage] (BetterFoliage-MC1.8.x-2.0.15.jar) 
	UCHIJAAAAAAAAA	BiomesOPlenty{3.0.0} [Biomes O' Plenty] (BiomesOPlenty-1.8.9-3.0.0.2004-universal.jar) 
	UCHIJAAAAAAAAA	DynamicLights{1.3.9} [Dynamic Lights] (DynamicLights-1.8.8.jar) 
	UCHIJAAAAAAAAA	DynamicLights_onFire{1.0.5} [Dynamic Lights Burning Entity Module] (DynamicLights-1.8.8.jar) 
	UCHIJAAAAAAAAA	DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module] (DynamicLights-1.8.8.jar) 
	UCHIJAAAAAAAAA	DynamicLights_dropItems{1.0.8} [Dynamic Lights EntityItem Module] (DynamicLights-1.8.8.jar) 
	UCHIJAAAAAAAAA	DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.8.8.jar) 
	UCHIJAAAAAAAAA	DynamicLights_mobEquipment{1.0.8} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.8.8.jar) 
	UCHIJAAAAAAAAA	DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.8.8.jar) 
	UCHIJAAAAAAAAA	DynamicLights_floodLights{1.0.2} [Dynamic Lights Flood Light] (DynamicLights-1.8.8.jar) 
	UCHIJAAAAAAAAA	DynamicLights_otherPlayers{1.0.7} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.8.8.jar) 
	UCHIJAAAAAAAAA	DynamicLights_thePlayer{1.1.3} [Dynamic Lights Player Light Module] (DynamicLights-1.8.8.jar) 
	UCHIJAAAAAAAAA	dsurround{2.0.5.6} [Dynamic Surroundings] (DynamicSurroundings-1.8.9-2.0.5.6.jar) 
	UCHIJAAAAAAAAA	fbp{2.4.0} [Fancy Block Particles] (FancyBlockParticles-1.8.9-2.4.0.jar) 
	UCHIJAAAAAAAAA	OWG{1.0.4} [Old World Gen] (OWG-1.0.4-1.8.9.jar) 
	UCHIJAAAAAAAAA	shouldersurfing{1.1} [Shoulder Surfing] (ShoulderSurfing-1.8.8_1.8.9-1.1.jar) 
	UCHIJAAAAAAAAA	soundfilters{0.8_for_1.8} [Sound Filters] (SoundFilters-0.8_for_1.8.jar) 
	Loaded coremods (and transformers): 
ShoulderPlugin (ShoulderSurfing-1.8.8_1.8.9-1.1.jar)
  com.teamderpy.shouldersurfing.asm.ShoulderTransformations
DLFMLCorePlugin (DynamicLights-1.8.8.jar)
  atomicstryker.dynamiclights.common.DLTransformer
BetterFoliageLoader (BetterFoliage-MC1.8.x-2.0.15.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
dsurroundcore (DynamicSurroundings-1.8.9-2.0.5.6.jar)
  org.blockartistry.mod.DynSurround.asm.Transformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 399.24' Renderer: 'GeForce GTX 1080 Ti/PCIe/SSE2'
	Launched Version: 1.8.9-forge1.8.9-11.15.1.2318-1.8.9
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1080 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 399.24, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: NostalgiaCraft1.7_Midbeta_1.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
	OptiFine Version: OptiFine_1.8.9_HD_U_I7
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: SEUS v11.0.zip
	OpenGlVersion: 4.6.0 NVIDIA 399.24
	OpenGlRenderer: GeForce GTX 1080 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by Adahel** [comment]
While a solution does not arrive, I'm going to prevent the particle that closing the game, by writing to line 260 of class FBPParticleManager: !(blockState.getBlock() instanceof BlockBOPPlant).

**Comment by TominoCZ** [comment]
I found the issue, it was my fault. It's fixed now.
FBP-2.4.1 is out now.
