### ISSUE TITLE
Particle system stops working eventually

### ISSUE THREAD

**Issue by Kevadroz** [TominoCZ/FancyBlockParticles#110]
## Steps to reproduce issue:

1. (With the mods): [Pastebin](https://pastebin.com/TR1KS1xe)  (Pastebin paste expires in a month (29 of december, 2018))
2. Load a world,
3. ensure mobs can spawn,
4. wait for a little,
5. the wole particle system stoped working!
6. Messing with FBP and OptiFine settings fixes it temporally sometimes

## Forge Version (e.g. 2604): 2772

May be because of 'Champions', the issue only appeared after i installed it, (i also installed some other mods at the same time, for example 'Deep Mob Learning' so i don't really know what mod is causing it).
The only reason i think it can be champions is because of the particles the mobs have. Also i noticed that the issue appeared only after champions 0.4.
No logs because the issue doesn't appear in logs (i checked)

**Comment by Kevadroz** [comment]
Nevermind, not FBP fault

**Comment by mxnmnm** [comment]
What caused it?  I'd like to know since I'm dealing with this as well.  Thanks!
