### ISSUE TITLE
Odd/Incorrect Color Display

### ISSUE THREAD

**Issue by Jimbob15082** [TominoCZ/FancyBlockParticles#12]
Colors doesn't seem to be displaying correctly. Minecraft Version 1.12, FBP Version 2.2.2(?)

It seems like resource packs affect it in some manner, however removing all resource packs doesn't fix the issue. Also particles that have different colors based on biomes such as grass are especially messed up.

Mods that I think might be causing issues are Better Foliage and Optifine, Other than that I don't think any of my other mods affect FBP. (Plus I'm too lazy to write them all down :^P) 

Other data that I have on hand:
Console isn't freaking out, liteloader is installed, graphics card is up to date, Shaders (provided by Optifine) doesn't seem to affect FBP, default FBP settings, optifine settings can be provided if necessary.

Screenshots (No Modified Textures):
![2017-07-27_00 35 14](https://user-images.githubusercontent.com/18095912/28656820-a2feb462-7269-11e7-9462-792174a8157f.png)
Grass
![2017-07-27_00 35 30](https://user-images.githubusercontent.com/18095912/28656822-a301a500-7269-11e7-9e11-153815ff076e.png)
Grass and Course Dirt
![2017-07-27_00 55 43](https://user-images.githubusercontent.com/18095912/28656821-a2ff719a-7269-11e7-9485-cc70b80f12c0.png)
Redstone

**Comment by TominoCZ** [comment]
That's strange.. It could be because the mod was made for an early version of Forge.. That leads me to the following two questions:
What version of Forge are you running?
Does this happen with the regular particles(when the mod is disabled)?

Please zip and upload your mods folder to somewhere and link me to it.. I will look more into it once I can.

**Comment by Jimbob15082** [comment]
It seems like it was because I didn't update forge, I'm sure it's probably fixed now. Sorry for the late reply.
