### ISSUE TITLE
2.3.0 Smoke Particles incompatible with Advanced Chimneys

### ISSUE THREAD

**Issue by D3nnis3n** [TominoCZ/FancyBlockParticles#13]
Hey, Advanced Chimneys has a smoker block to simulate chimneys. With your newest Version the new particles are rendered, but only in the first block. Settings like height, intensity, etc. are ignored and i can't seem to get the smoke to get higher or something like that, i hope you understand.

**Comment by TominoCZ** [comment]
Fixed everything!
https://s1.postimg.org/3exc7ipb5p/2017-10-02_03.31.47.png

Will release the new version once i fix all the issues ;)
