### ISSUE TITLE
Client only crash when placing architecture bench with ArchitectureCraft as of version 2.3 of fbp

### ISSUE THREAD

**Issue by D3nnis3n** [TominoCZ/FancyBlockParticles#14]
Your newest Version causes a Crash when placing an architecture bench, but only on the Client. After reloading the bench is there. Unfortunatley i have not got the Crash log, but i'll install your newest Version again tonight to get it to you.

**Comment by TominoCZ** [comment]
The mod is entirely client side and there is also an option to add an exception for blocks that you don't wan't to animate in the Fancy Block Particles menu[press P] (assuming it's the block placing animation that is causing the crash).

In case you can't find the block in the FBP menu, you can add it manually into the exceptions config in .minecraft/config/FBP/AnimBlockExceptions.txt.

I'll keep this one open and try to fix it if possible..

**Comment by TominoCZ** [comment]
Fixing this bug, I've actually discovered an another game-crashing bug..
Fixed both of them :)
