### ISSUE TITLE
[1.10.2] Crash when right-clicking any block

### ISSUE THREAD

**Issue by ACGaming** [TominoCZ/FancyBlockParticles#16]
- Minecraft Forge 12.18.3.2488
- OptiFine HD U E3
- Fancy Block Particles 2.3.0

https://paste.ubuntu.com/25691033

**Comment by TominoCZ** [comment]
Yes.. I've already received reports of the same bug many times and already fixed it. Will release it soon.

**Comment by ACGaming** [comment]
Alright!
