### ISSUE TITLE
[1.12.2] Missing texture when placing Shulker Box & Shadow underneath block for a split second when placed.

### ISSUE THREAD

**Issue by Gbergz** [TominoCZ/FancyBlockParticles#17]
When placing a shulker box. any box.
a missing texture appears.
Playing with the latest version of the mod.
GIF Here showing it: [Gfycat](https://gfycat.com/OblongFlamboyantCockatiel)

EDIT: Also when placing any block a little shadow is popping up underneath it, dunno if this is intentional or a feature, it looks off so i'll just report it here too. :) GIF: [Gfycat](https://gfycat.com/ForkedSereneCuttlefish)

**Comment by TominoCZ** [comment]
Add the Shulker Box to the exceptions.
