### ISSUE TITLE
Issues with Rain

### ISSUE THREAD

**Issue by D3nnis3n** [TominoCZ/FancyBlockParticles#20]
Your rain particles are falling through solid blocks and slabs, while vanilla rain particles do not. This does happen in most of our houses on the highest Level of These houses - directly under the Roof. So if you are there, it rains into your house.

Also i think there are too less rain particles. You don't really get that it's raining. I would at least double the particles.

**Comment by D3nnis3n** [comment]
As i saw: Rain falls even into the part of the Building that is on the ground or even beneath - it just get's lesser rain down there.

**Comment by TominoCZ** [comment]
I've fixed it.. stay tuned for the upcoming version! :)

**Comment by TominoCZ** [comment]
fixed in version 2.3.2.
