### ISSUE TITLE
Configurability for each feature you have

### ISSUE THREAD

**Issue by D3nnis3n** [TominoCZ/FancyBlockParticles#21]
As the block placing Animation is pretty Buggy for some blocks (air until the block is there) and e.g. the rain is just bareley visible it would be nice if we could disable some of the altered particles you add.

For example block breaking particles work perfectly, i'd like to use these. I'd also like to use the smoke particles, when they are fixed for advanced chimneys. I'd also like to use rain if there are more particles, but i'd like to disable that if not. Also i'd like to disable placing particles.

**Comment by TominoCZ** [comment]
There is a FBP menu which you open with 'P' and you can disable the fancy weather there.
Although I've just finished working on the new settings in the FBP menu. 

All settings you mentioned will be in the upcoming version :)

**Comment by TominoCZ** [comment]
done in version 2.3.2.
