### ISSUE TITLE
Client Crash when placing a Immersive Engineering Razor Wire

### ISSUE THREAD

**Issue by D3nnis3n** [TominoCZ/FancyBlockParticles#23]
When you place an razor wire of IE, the game crashes without any Crash log. Just shuts down and nothing is in there. As the graphic Looks glitched, i suspect this is because of FancyBlockParticles in Version 2.3 or higher.

**Comment by TominoCZ** [comment]
always provide the crashlog please.

**Comment by TominoCZ** [comment]
There's no way that there's no crashlog.. it might be in a log file.. It must be logged somewhere.

**Comment by D3nnis3n** [comment]
Nope, no crashlog. Shutsdown with a lot of empty loglines. I had several
complicated crashes in tje last days that did not generate crashlogs and
only wrote "considered crashed".

Am 10.10.2017 08:41 schrieb "TominoCZ" <notifications@github.com>:

**Comment by TominoCZ** [comment]
Wait.. are you using FBP-2.3.0? If so, make sure to use the latest version of the mod.

**Comment by D3nnis3n** [comment]
No. 2.3.1. Now Downgraded to 2.2.2.

Am 10.10.2017 11:14 schrieb "TominoCZ" <notifications@github.com>:

**Comment by TominoCZ** [comment]
by the way you could've just disabled Fancy Place Animation in the FBP menu..

**Comment by D3nnis3n** [comment]
Yeh. Maybe. But we got no keys left in our modpack, so it hasn't one and i didn't even look for that.

**Comment by D3nnis3n** [comment]
@TominoCZ  
See: https://github.com/TominoCZ/FancyBlockParticles/issues/21
I did not even know there is a configuration, therefore i suggested it :D But i Need a config, and in the config there is no such entries. We got no keys left for your in-game-menu.

**Comment by D3nnis3n** [comment]
Also - i got a internal clan-modpack with many users. I can't just disable that for me, i Need to apply that to everyone, so this is not a fix for me.

**Comment by TominoCZ** [comment]
fixed in version 2.3.2.
