### ISSUE TITLE
Blinking Blocks

### ISSUE THREAD

**Issue by ericksantos12** [TominoCZ/FancyBlockParticles#24]
when i put a block, the block blinks, this is weird and isnt cool 😢

**Comment by TominoCZ** [comment]
Explain what it's doing.

**Comment by ericksantos12** [comment]
When i place a block in the ground, it blinks for a short time, this is very weird, that annoys me

**Comment by TominoCZ** [comment]
What minecraft version?
What mod version?

Provide a screenshot if you can.

**Comment by ericksantos12** [comment]
Minecraft version: 1.12.2
Mod version: 2.3.1

I have some screenshots, but is better a gif, because it blinks for a short time
![2017-10-13_13 20 16](https://user-images.githubusercontent.com/16109127/31556004-8e6e6d88-b019-11e7-90eb-89570422b0e0.png)
![2017-10-13_13 20 17](https://user-images.githubusercontent.com/16109127/31556005-8e9400c0-b019-11e7-9998-78db575fc5e6.png)

**Comment by TominoCZ** [comment]
hmm.. did you try it with default shaders?

**Comment by SwordShaman** [comment]
I'm getting the same blinking when placing blocks.  Same minecraft and mod version as above.  I'm also using shaders, though different than the user's above.

**Comment by ericksantos12** [comment]
i tried without shaders and it continues with the same error(Sorry my grammar, im braziliam)

**Comment by D3nnis3n** [comment]
I got that issue with most mods, too.

**Comment by D3nnis3n** [comment]
It's the same issue as this: https://github.com/TominoCZ/FancyBlockParticles/issues/22

**Comment by Harrison015** [comment]
Here is what it looks like:
https://gyazo.com/5d999b063b4389f1523293a16bfaaef9
Not using any shaders and on 1.12.2 , newest mod version

**Comment by TominoCZ** [comment]
should be fixed in version 2.3.2.
