### ISSUE TITLE
Crash When Using Malisis' Doors (Core)

### ISSUE THREAD

**Issue by BranTuna** [TominoCZ/FancyBlockParticles#25]
**MC Version:** 1.12.2
**Forge Version:** 14.23.0.2515
**Fancy Block Particles Version:** 2.3.1
**Malisis Doors Version:** 7.1.1
**Malisis Core Version:** 6.1.7
**Crash Report:** [Click Here](https://pastebin.com/9WYdrcN2)
**Description:**

_Malisis' mods don't seem to like it when trying to open door with another door in hand. Ordinastie suggested it was Fancy Block Particles doing the crash._

**Comment by TominoCZ** [comment]
Yes.. There's been many reports on this exact same issue, it will be fixed in the upcoming version.
