### ISSUE TITLE
[Request] 1.12.2 Config Option

### ISSUE THREAD

**Issue by GWSheridan** [TominoCZ/FancyBlockParticles#26]
config option able to turn the partials off for some types of blocks (BoP ash block for example) 
Just like the block placing option

**Comment by TominoCZ** [comment]
I'll see what I can do :)

**Comment by TominoCZ** [comment]
done in version 2.3.2.

**Comment by GWSheridan** [comment]
removing particles does not work for some reason 

https://gyazo.com/93a1ef6d7d732eb664be1ebbec6dc6ba
