### ISSUE TITLE
[1.12.2] Flashing blocks

### ISSUE THREAD

**Issue by LiskoSlayer63** [TominoCZ/FancyBlockParticles#27]
When placing any block it flashes the block to transparent and then normal. I first thought that this was caused by OptiFine and/or some shaders I was using but it stopped doing this after I removed Fancy Block Particles.

**Demonstration:**
![fbp_bug](https://user-images.githubusercontent.com/10125529/33008460-d4abb6c2-cddb-11e7-829f-d65a2e40fa2b.gif)

**Comment by TominoCZ** [comment]
That's the **placing animation**. There **is** an option to disable it in the **FBP menu**.
I'm currently working on it..

There's a few things I need to know:
1. FBP version
2. forge build version
3. Whether VBOs are ON
4. Whether Smooth Lighting is ON
5. What shaders you're using
6. The optifine config settings (post the config files here)

**Comment by LiskoSlayer63** [comment]
@TominoCZ Didn't realize that this is a feature update which can be turned off.

**FBP version**: 2.3.1
**OptiFine version**: HD U C6
**Forge version**: 14.23.0.2548
**VBO**: ON
**Smooth Lighting**: Maximum
**Shaders**: SEUS v11

I also tried it without shaders, makes no difference.

**Comment by TominoCZ** [comment]
Thanks. The upcoming version will have this issue fixed :)
