### ISSUE TITLE
[1.12.2] Flashing particles

### ISSUE THREAD

**Issue by nigrum-dente** [TominoCZ/FancyBlockParticles#28]
Okay, let's begin.

Mod version is: 2.3.1
Forge version is: 14.23.0.2531

The pack I'm playing is All the mods3 with a handful of mod added in it.

And since picture work best at showing what is happening:

![flashingblock 1](https://user-images.githubusercontent.com/28484707/33180486-2b5e313c-d06d-11e7-86ea-9892bbc56e82.gif)

**Comment by TominoCZ** [comment]
I've had something similar happen to me earlier this week.. Enabling VBOs helped..
Though I'm not sure how the particles went transparent there...

I'll investigate ;)

**Comment by nigrum-dente** [comment]
I have VBOs enabled by default on this instance.
I tried switching it on or off and the issue stayed.

**Comment by TominoCZ** [comment]
(hopefully)fixed in version 2.3.2.

**Comment by TominoCZ** [comment]
Did the new version fix the issue?

**Comment by nigrum-dente** [comment]
Yeah it did.

Thanks for the fix.

**Comment by TominoCZ** [comment]
np
