### ISSUE TITLE
Fast Falling Particles?

### ISSUE THREAD

**Issue by SylisMC** [TominoCZ/FancyBlockParticles#3]
Hey. Not sure if this is really a bug. but it defiantly looks weird and unrealistic.

MC v-1.11.2
Forge v-13.20.0.2228
Mod v-2.0.2, 

particles seem to fall really really quickly after you break the block under them. as if the speed that they should be felling at. doesn't get reset when they are on the ground.

example
If i broke dirt, and the particles were on top of a log. and then i also broke the log. the dirt particles would hit the ground first

took some screenshots so you cans see what im talking about

img01 http://i.imgur.com/T3amm5F.png
img02 http://i.imgur.com/pdiCbrC.png
img03 http://i.imgur.com/J8vUyzi.png

Awesome mod btw! love it (:

**Comment by TominoCZ** [comment]
That's not a bug. I know exactly what you mean and that's just how minecraft particles work fact.
