### ISSUE TITLE
[1.12.2 - 2.3.2] Bibliocraf block do not remeber rotation

### ISSUE THREAD

**Issue by nigrum-dente** [TominoCZ/FancyBlockParticles#30]
Why hello it's me again !

Just in case you are reading this issue first, 2.3.2 did fix the bug with the flashing transparent block.

Bad news is in version 2.3.2, **every** block of bibliocraft when placed do not remember their rotation.

A gif to illustrate:
![labelorientation](https://user-images.githubusercontent.com/28484707/33269119-de93466a-d37f-11e7-86d5-6f7757d33596.gif)

**Comment by TominoCZ** [comment]
It seems that there is no way to make the placement animation work properly..
There is a way to make it less buggy, but it makes the animation delayed, making it pointless.

This feature is something that is almost impossible to do in Minecraft without extremely advanced programming knowledge. It wasn't my idea to add it to the mod after all..

I will leave this issue open in case I manage to actually make it work one day :D

**Comment by TominoCZ** [comment]
I have managed to find a way around... Fixed it. 
Though there is still no animation...
