### ISSUE TITLE
Invisible block placement.

### ISSUE THREAD

**Issue by Draylynn** [TominoCZ/FancyBlockParticles#31]
1.12.2
FBP-2.3.3
Optifine HD U C6

This affected my husband before it affected me, the next day I also started experiencing problems. I haven't edited any of the FBP configs, they're running as stock default. Randomly when placing blocks, saplings etc they will be invisible, we can break the invisible block to retrieve it.
Removing FBP stops invisible blocks.
FBP with Optifine (SEUS/Sildurs shaders) looks absolutely amazing and immersive, I hope you can find the cause.

**Comment by TominoCZ** [comment]
Well you could've just disabled the mod in the FBP menu.. Everyone seems to not know that that is an option too.. xD

Anyways.. I think I know what is causing it... Try this one:
https://www.mediafire.com/file/hpx7r7sti7zj6ks/FancyBlockParticles-2.3.4_indev.jar

**Comment by Draylynn** [comment]
Straight off the bat, I'm not having any issues, but I'll distribute it to my hubby's computer and we'll play around tonight to see if we run into the issue. I think I'm noticing the block placement animation is ever so 'slightly' different? But still in a cool way 👍 
Thanks for the quick response, the world needs faster-acting devs like you around! =3
Will keep you updated.

**Comment by TominoCZ** [comment]
Thanks! :3 
Yes.. I made the animation look more interesting in 2.3.3.. :D

**Comment by TominoCZ** [comment]
released version 2.3.4 along with other small changes and fixes :)
