### ISSUE TITLE
Placing blocks: Sometimes causes ghost blocks. FBP 2.3.1

### ISSUE THREAD

**Issue by Antmanofgod** [TominoCZ/FancyBlockParticles#34]
When the mod is enabled, while attempting to place a block the block will disappear or become invisible. The only way the become visible again is by leaving the chunk and returning to it. However when I disable the mod, this issue does not happen.

**Comment by TominoCZ** [comment]
Yes.. that's a pretty old version.. the animation has gone through lots of changes and fixes over the newer versions.

Update to version 2.3.5 and see what's new ;)
