### ISSUE TITLE
[1.12.2] Botania flowers don't render correctly with this mod

### ISSUE THREAD

**Issue by razage** [TominoCZ/FancyBlockParticles#35]
I can't say what exactly causes it, but Botania flowers do not render correctly and won't work. Relogging, on single player at least, fixes placed flowers.
![example](https://user-images.githubusercontent.com/9331220/33799869-886947f2-dcf9-11e7-839a-94b4a1ac72b7.png)

**Comment by razage** [comment]
There's an issue open on [Botania's repository](https://github.com/Vazkii/Botania/issues/2452) related to this as well. It _seems_ like this is caused by a tag not being applied when it is placed or something like that.

**Comment by TominoCZ** [comment]
What version of the mod are you using?

**Comment by razage** [comment]
I would have been using 2.3.5 for MC 1.12.2

**Comment by TominoCZ** [comment]
You **_would_** or **_you are_** using version 2.3.5...? :D

**Comment by razage** [comment]
Sorry lol. I used past tense because I had to remove it for my modpack's initial release. But I guess that could be interpreted as I _am_ using 2.3.5

**Comment by TominoCZ** [comment]
ok ok..
Hmm.. it's weird though.. this shouldn't happen.. I'll see what I can do.

By the way.. you can always just add the block to exceptions.. the exception feature is mentioned on the mod page.

**Comment by razage** [comment]
Didn't notice that, so I guess that's an ok solution. But it would involve adding 50+ blocks I believe, when including all botania flowers, mekanism pipes, and mekanism storage.

**Comment by Lt1489** [comment]
I've found this is also an issue with quark chests, I've found a solution to the bug. It seems to be "Fancy Place" that breaks the texture. So if you turn off "Fancy Place", it should fix the missing textures when you replace the blocks.

**Comment by Zsashas** [comment]
Problem is, the exceptions don't stay added when the game is reloaded.

**Comment by Lt1489** [comment]
@Zsashas For now, just disable "Fancy Place" and the issue should be fixed.

**Comment by TominoCZ** [comment]
Ok.. I just found the reason why the mod even let this block to animate..
The fancy place feature has a little sub-feature that checks whehter the block model can be animated or not.
This sub-feature had one little mistake I completely missed.

Anyways.. once I release the new version, this shouldn't happen anymore. The blocks that can't be animated will not animate(much like the one mentioned in this issue).
