### ISSUE TITLE
TiCon Drying Racks always face the same way until game is reloaded

### ISSUE THREAD

**Issue by Zsashas** [TominoCZ/FancyBlockParticles#37]
They always face the same direction, no matter which way I place them, so I'll have them floating in front of the wall or sticking out, until a reload.

**Comment by TominoCZ** [comment]
What version of the mod are you using?

By the way.. you can always add blocks to exceptions so it's not being animated when you place it. The block exceptions feature is mentioned on the mod page.

**Comment by Zsashas** [comment]
Did not know this...good to know.
