### ISSUE TITLE
Mod interaction crash with Artisan Worktables

### ISSUE THREAD

**Issue by codetaylor** [TominoCZ/FancyBlockParticles#39]
Hi, I recently received a crash report for my mod Artisan Worktables. This crash only occurs with Fancy Block Particles installed.

I was able to reproduce the crash using version FBP 2.3.5 and the latest version of my mod.

Here is a snippet from the crash log:
```
java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class com.codetaylor.mc.artisanworktables.modules.worktables.block.BlockWorktable$EnumType, values=[TAILOR, CARPENTER, MASON, BLACKSMITH, JEWELER, BASIC]} as it does not exist in BlockStateContainer{block=null, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
	at com.codetaylor.mc.artisanworktables.modules.worktables.block.BlockWorktable.getSoundType(BlockWorktable.java:54)
	at com.TominoCZ.FBP.block.FBPAnimationDummyBlock.getSoundType(FBPAnimationDummyBlock.java:291)
	at net.minecraft.item.ItemBlock.func_180614_a(ItemBlock.java:57)
```

Full crash logs and a description of the issue from the OP located here:
https://github.com/codetaylor/artisan-worktables/issues/8

Here is the method in my `BlockWorktable` that `FBPAnimationDummyBlock#getSoundType` delegates to:
https://github.com/codetaylor/artisan-worktables/blob/master/src/main/java/com/codetaylor/mc/artisanworktables/modules/worktables/block/BlockWorktable.java#L50

The crash occurs whenever one of my worktables is placed in the world.

I would appreciate any insight you might have as to why this is happening. Thanks for your time!

**Comment by codetaylor** [comment]
If I disable the fancy place animations, the crash goes away:

```
fancyPlaceAnim=false
```

**Comment by TominoCZ** [comment]
Yes, I know this is happening and I've already fixed it. I will release the new version when It's ready.
