### ISSUE TITLE
Punching enderIO conduits crashes the game

### ISSUE THREAD

**Issue by bluefutureMC** [TominoCZ/FancyBlockParticles#4]
Yea, the title is all there is to say, punching enderIO conduits crashes the game.

So yea, thanks

**Comment by TominoCZ** [comment]
I can't find the problem without a crashlog.

**Comment by bluefutureMC** [comment]
Crash:
The game crashed whilst unexpected error
Error: java.lang.ClassCastException: com.TominoCZ.FBP.particle.FBPParticle cannot be cast to net.minecraft.client.particle.ParticleDigging

Crash Log:
https://pastebin.com/zW3J2vTV

**Comment by TominoCZ** [comment]
hm.. that's wierd.. I can't tell what went wrong and I'm not sure how to fix this.. Anyways.. I'll see what I can do about it ;)

**Comment by hanakocz** [comment]
Well that mod adds their own particles to their items. -> https://github.com/SleepyTrousers/EnderIO/blob/master/src/main/java/crazypants/enderio/conduit/BlockConduitBundle.java

Thing is that their side expects vanilla particles to change them to their own particles, but it finds your particles, which are not same at all, thus cannot be changed their way. You need to make there some checkings to not always change particles to your 3D ones (if they are not vanilla ones), or contact authors of EnderIO to let their particles check if your particles are in, and if, change them accordingly to your code. However, The good practice would be to intercept any mod's change to default paticles and translate it to the new ones.

**Comment by LapisSea** [comment]
I think an optimal solution here would be a cross mod interface using `Loader.isModLoaded` and adding extra behavior if EnderIO is loaded. This way you can counter the unexpected particles but also keep the performance at maximum when mod is not present.

**Comment by hanakocz** [comment]
@LapisSea there might be infinite number of mods changing their block's particles. Then maintaning it would be really painful job. Only solution capable to deal with them all at once is proper way.

**Comment by LapisSea** [comment]
Yes that is right. You can use asm to somewhat fix this without throwing away regards for performance.
But if there is a mod that does not play by the rules (i am a big time offender of this) than you can't assume that the breaking particle is going to be an instance of  `EntityDiggingFX`.

Now I realize that I didn't point it that I meant in border sense.

**Comment by TominoCZ** [comment]
Well what it said was that my particle cannot be cast to ParticleDigging... so what I'm testing right now is that I made my particle extend ParticleDigging instead of Particle. I hope it'll work

**Comment by TominoCZ** [comment]
Ok I seem to have fixed everything. I will release the new version soon.
