### ISSUE TITLE
Cant pick up items

### ISSUE THREAD

**Issue by erikwonderson** [TominoCZ/FancyBlockParticles#40]
Hi! I cant pick up items with this mod...why???
When i removed it, it works just fine.

**Comment by TominoCZ** [comment]
Could yyou be more specific?

**Comment by TominoCZ** [comment]
Could you please provide more information about your issue? From what you've told me, I have nothing to work with.

**Comment by erikwonderson** [comment]
Sorry for this e-mail. It wasn't your mods fault if i can say that.
It was other mods issue and when i drag out that mod the game was worked
just fine. So sorry again for this e-mail. It wasn't for you. Your mod is
perfectly working just fine.

2018-01-21 17:22 GMT+01:00 TominoCZ <notifications@github.com>:

**Comment by erikwonderson** [comment]
Opened #41.

2018-01-23 13:55 GMT+01:00 TominoCZ <notifications@github.com>:
