### ISSUE TITLE
Fading block

### ISSUE THREAD

**Issue by TacoGuyAT** [TominoCZ/FancyBlockParticles#42]
Sometimes fancy placing a bit fading, when it's in block

**Comment by TominoCZ** [comment]
I am not sure what you mean by that. Explain in more detail please.

**Comment by TacoGuyAT** [comment]
https://imgur.com/a/ko5S7

**Comment by TominoCZ** [comment]
Oh.. Disable Smooth Lighting to prevent that.

**Comment by TacoGuyAT** [comment]
so it is not fixable without disabling smooth lighting?

**Comment by TominoCZ** [comment]
I could make it look the way it looks with smooth ligting disabled all the time, but if you look at the sides of the block in the same scenerio, you will see that the block has some of it's sides black..

**Comment by TacoGuyAT** [comment]
Ok then

**Comment by TacoGuyAT** [comment]
There some more bugs: https://youtu.be/7qGVuolZDq8

**Comment by TominoCZ** [comment]
That's the video from the other issue you've submitted, which I have already replied to..

Anyways.. I will add a button so you can change the render mode of the animation from the FBP menu :)
