### ISSUE TITLE
Crash with GlobalXP and WAILA

### ISSUE THREAD

**Issue by bl4ckscor3** [TominoCZ/FancyBlockParticles#43]
The XP Block uses WAILA to display its contents. When placing it down (Fancy Place Animation enabled) and keep looking at it, the game crashes with the following crash report. When looking away quick enough, the game does not crash. When adding the XP Block to the block execution list of the place animation, the game does not crash upon placing it down either.

<details>
<summary>Crash report</summary>

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  SignPictureCorePlugin (SignPicture-1.12-2.8.1-universal.jar)
  BlurPlugin (Blur-1.0.4-14.jar)
  MalisisCorePlugin (malisiscore-1.12-6.0.4.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.7.2.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 1/21/18 7:09 PM
Description: Unexpected error

java.lang.ClassCastException: com.TominoCZ.FBP.block.FBPAnimationDummyBlock cannot be cast to bl4ckscor3.mod.globalxp.blocks.XPBlock
	at bl4ckscor3.mod.globalxp.imc.waila.WailaDataProvider.getWailaStack(WailaDataProvider.java:55)
	at mcp.mobius.waila.overlay.RayTracing.getIdentifierItems(RayTracing.java:115)
	at mcp.mobius.waila.overlay.RayTracing.getIdentifierStack(RayTracing.java:73)
	at mcp.mobius.waila.overlay.RayTracing.getTargetStack(RayTracing.java:57)
	at mcp.mobius.waila.overlay.DecoratorRenderer.onRenderWorldLast(DecoratorRenderer.java:27)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_35_DecoratorRenderer_onRenderWorldLast_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:163)
	at sun.reflect.GeneratedMethodAccessor71.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.callVoid(Reflector.java:555)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1928)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1606)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1377)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at bl4ckscor3.mod.globalxp.imc.waila.WailaDataProvider.getWailaStack(WailaDataProvider.java:55)
	at mcp.mobius.waila.overlay.RayTracing.getIdentifierItems(RayTracing.java:115)
	at mcp.mobius.waila.overlay.RayTracing.getIdentifierStack(RayTracing.java:73)
	at mcp.mobius.waila.overlay.RayTracing.getTargetStack(RayTracing.java:57)
	at mcp.mobius.waila.overlay.DecoratorRenderer.onRenderWorldLast(DecoratorRenderer.java:27)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_35_DecoratorRenderer_onRenderWorldLast_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:163)
	at sun.reflect.GeneratedMethodAccessor71.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.callVoid(Reflector.java:555)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1928)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1606)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['bl4ckscor3'/282, l='MpServer', x=-158.33, y=64.00, z=267.29]]
	Chunk stats: MultiplayerChunkCache: 1632, 1632
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-112,64,256), Chunk: (at 0,4,0 in -7,16; contains blocks -112,0,256 to -97,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 4295 game time, 4295 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 116 total; [EntityLatchedRenderer['unknown'/533, l='MpServer', x=-158.33, y=64.00, z=267.29], EntityItem['item.tile.xp_block'/534, l='MpServer', x=-159.17, y=64.00, z=263.76], EntityItem['item.tile.xp_block'/536, l='MpServer', x=-156.81, y=64.00, z=263.90], EntityPlayerSP['bl4ckscor3'/282, l='MpServer', x=-158.33, y=64.00, z=267.29], EntityZombie['Zombie'/50, l='MpServer', x=-234.70, y=18.01, z=236.92], EntityHorse['Horse'/51, l='MpServer', x=-233.83, y=69.00, z=253.14], EntityHorse['Horse'/52, l='MpServer', x=-234.20, y=69.00, z=255.93], EntityZombie['Zombie'/53, l='MpServer', x=-235.26, y=24.00, z=268.50], EntityZombie['Zombie'/54, l='MpServer', x=-227.50, y=31.00, z=258.50], EntityZombie['Zombie'/55, l='MpServer', x=-233.30, y=18.38, z=274.30], EntityChicken['Chicken'/58, l='MpServer', x=-226.60, y=68.00, z=283.12], EntityChicken['Chicken'/59, l='MpServer', x=-229.50, y=69.00, z=288.50], EntityChicken['Chicken'/60, l='MpServer', x=-230.17, y=68.00, z=293.22], EntityZombie['Zombie'/61, l='MpServer', x=-226.50, y=20.00, z=305.50], EntityHorse['Horse'/68, l='MpServer', x=-213.23, y=66.00, z=248.47], EntityEnderman['Enderman'/69, l='MpServer', x=-220.50, y=31.00, z=258.50], EntityBat['Bat'/70, l='MpServer', x=-223.25, y=36.10, z=265.75], EntityChicken['Chicken'/71, l='MpServer', x=-218.57, y=67.00, z=287.60], EntityPig['Pig'/72, l='MpServer', x=-214.50, y=63.00, z=314.50], EntityPig['Pig'/73, l='MpServer', x=-211.47, y=63.00, z=319.71], EntityPig['Pig'/74, l='MpServer', x=-211.61, y=64.00, z=306.71], EntityPig['Pig'/75, l='MpServer', x=-208.78, y=63.00, z=324.23], EntityZombie['Zombie'/76, l='MpServer', x=-208.50, y=50.00, z=329.50], EntityItem['item.tile.mushroom'/85, l='MpServer', x=-193.77, y=20.00, z=203.77], EntityEnderman['Enderman'/86, l='MpServer', x=-198.54, y=30.00, z=218.28], EntityChicken['Chicken'/87, l='MpServer', x=-205.48, y=67.00, z=233.81], EntityChicken['Chicken'/88, l='MpServer', x=-192.50, y=65.00, z=235.86], EntitySkeleton['Skeleton'/89, l='MpServer', x=-207.71, y=41.00, z=269.47], EntityItem['item.tile.torch'/90, l='MpServer', x=-203.17, y=31.00, z=272.13], EntitySkeleton['Skeleton'/91, l='MpServer', x=-205.10, y=29.00, z=284.55], EntitySkeleton['Skeleton'/92, l='MpServer', x=-192.75, y=35.00, z=276.50], EntitySkeleton['Skeleton'/93, l='MpServer', x=-197.51, y=35.00, z=273.75], EntityZombieVillager['Zombie Villager'/94, l='MpServer', x=-201.21, y=35.00, z=276.51], EntitySpider['Spider'/95, l='MpServer', x=-207.50, y=51.00, z=298.50], EntityZombie['Zombie'/96, l='MpServer', x=-201.56, y=52.00, z=301.22], EntitySkeleton['Skeleton'/97, l='MpServer', x=-199.34, y=20.00, z=305.50], EntityZombie['Zombie'/99, l='MpServer', x=-188.51, y=12.00, z=196.73], EntityZombie['Zombie'/100, l='MpServer', x=-186.50, y=29.00, z=204.50], EntityChicken['Chicken'/101, l='MpServer', x=-187.53, y=64.00, z=230.80], EntityChicken['Chicken'/102, l='MpServer', x=-189.59, y=64.00, z=260.21], EntitySkeleton['Skeleton'/103, l='MpServer', x=-187.50, y=29.00, z=275.50], EntitySkeleton['Skeleton'/104, l='MpServer', x=-186.25, y=18.00, z=274.53], EntitySkeleton['Skeleton'/105, l='MpServer', x=-179.05, y=33.00, z=278.62], EntityEnderman['Enderman'/106, l='MpServer', x=-170.76, y=38.97, z=266.50], EntityCreeper['Creeper'/107, l='MpServer', x=-176.60, y=21.00, z=294.85], EntityZombie['Zombie'/108, l='MpServer', x=-181.44, y=15.00, z=310.24], EntityZombie['Zombie'/109, l='MpServer', x=-178.50, y=20.00, z=307.50], EntityDonkey['Donkey'/110, l='MpServer', x=-179.73, y=64.00, z=315.94], EntityChicken['Chicken'/111, l='MpServer', x=-186.71, y=63.00, z=337.87], EntityZombie['Zombie'/121, l='MpServer', x=-163.64, y=22.00, z=212.70], EntitySkeleton['Skeleton'/122, l='MpServer', x=-163.77, y=18.00, z=224.50], EntityChicken['Chicken'/123, l='MpServer', x=-175.17, y=64.00, z=234.59], EntitySkeleton['Skeleton'/124, l='MpServer', x=-174.50, y=26.00, z=266.50], EntitySkeleton['Skeleton'/125, l='MpServer', x=-161.27, y=30.00, z=265.50], EntityZombie['Zombie'/126, l='MpServer', x=-155.74, y=40.00, z=259.78], EntityChicken['Chicken'/127, l='MpServer', x=-162.15, y=64.00, z=266.23], EntityCreeper['Creeper'/128, l='MpServer', x=-166.81, y=25.00, z=282.53], EntityCreeper['Creeper'/129, l='MpServer', x=-170.83, y=31.00, z=273.48], EntityCreeper['Creeper'/130, l='MpServer', x=-174.50, y=21.00, z=292.50], EntityZombie['Zombie'/131, l='MpServer', x=-164.50, y=27.00, z=301.50], EntitySkeleton['Skeleton'/132, l='MpServer', x=-161.50, y=27.00, z=300.50], EntityChicken['Chicken'/133, l='MpServer', x=-155.39, y=63.00, z=331.13], EntityChicken['Chicken'/134, l='MpServer', x=-163.36, y=64.00, z=336.01], EntitySkeleton['Skeleton'/135, l='MpServer', x=-159.50, y=19.00, z=215.67], EntityCreeper['Creeper'/136, l='MpServer', x=-158.58, y=23.00, z=213.12], EntityBat['Bat'/137, l='MpServer', x=-136.25, y=48.01, z=234.28], EntitySkeleton['Skeleton'/138, l='MpServer', x=-154.50, y=49.00, z=226.50], EntityZombie['Zombie'/139, l='MpServer', x=-150.19, y=48.00, z=224.50], EntityZombie['Zombie'/140, l='MpServer', x=-159.50, y=48.00, z=234.50], EntityChicken['Chicken'/141, l='MpServer', x=-158.46, y=64.00, z=232.48], EntityCreeper['Creeper'/142, l='MpServer', x=-146.50, y=34.00, z=245.80], EntityZombie['Zombie'/143, l='MpServer', x=-158.57, y=43.00, z=242.80], EntityBat['Bat'/144, l='MpServer', x=-153.25, y=47.25, z=236.48], EntityBat['Bat'/145, l='MpServer', x=-159.25, y=45.10, z=258.25], EntityCreeper['Creeper'/146, l='MpServer', x=-150.19, y=40.00, z=261.50], EntityCow['Cow'/147, l='MpServer', x=-155.94, y=64.00, z=254.00], EntitySkeleton['Skeleton'/148, l='MpServer', x=-144.06, y=43.00, z=281.50], EntityBat['Bat'/149, l='MpServer', x=-154.42, y=41.49, z=276.20], EntityZombie['Zombie'/150, l='MpServer', x=-157.51, y=15.00, z=292.73], EntityCreeper['Creeper'/151, l='MpServer', x=-149.52, y=32.00, z=293.83], EntityCreeper['Creeper'/152, l='MpServer', x=-159.50, y=31.00, z=306.50], EntityChicken['Chicken'/154, l='MpServer', x=-162.24, y=64.00, z=336.54], EntityChicken['Chicken'/156, l='MpServer', x=-147.16, y=64.00, z=240.20], EntitySkeleton['Skeleton'/157, l='MpServer', x=-131.77, y=38.00, z=255.47], EntitySkeleton['Skeleton'/158, l='MpServer', x=-141.49, y=38.00, z=245.71], EntitySkeleton['Skeleton'/159, l='MpServer', x=-128.50, y=29.00, z=260.76], EntityCreeper['Creeper'/160, l='MpServer', x=-130.81, y=39.00, z=257.49], EntityCreeper['Creeper'/161, l='MpServer', x=-129.51, y=40.00, z=262.23], EntityCreeper['Creeper'/162, l='MpServer', x=-140.17, y=40.00, z=258.49], EntityEnderman['Enderman'/163, l='MpServer', x=-143.72, y=30.00, z=278.49], EntityCreeper['Creeper'/164, l='MpServer', x=-140.50, y=35.00, z=295.50], EntitySquid['Squid'/165, l='MpServer', x=-133.52, y=52.00, z=316.60], EntitySquid['Squid'/166, l='MpServer', x=-135.68, y=60.26, z=329.92], EntityBat['Bat'/170, l='MpServer', x=-116.46, y=27.10, z=213.75], EntityBat['Bat'/171, l='MpServer', x=-125.62, y=23.10, z=220.25], EntityBat['Bat'/172, l='MpServer', x=-123.85, y=25.00, z=209.32], EntityCreeper['Creeper'/173, l='MpServer', x=-123.50, y=49.00, z=214.50], EntityCow['Cow'/174, l='MpServer', x=-108.80, y=69.00, z=262.51], EntityCow['Cow'/175, l='MpServer', x=-116.82, y=66.00, z=257.48], EntityBat['Bat'/176, l='MpServer', x=-126.79, y=23.85, z=286.51], EntityCow['Cow'/177, l='MpServer', x=-113.77, y=67.00, z=274.50], EntitySquid['Squid'/178, l='MpServer', x=-123.23, y=59.76, z=315.11], EntityBat['Bat'/182, l='MpServer', x=-97.25, y=45.03, z=201.25], EntityCreeper['Creeper'/183, l='MpServer', x=-108.20, y=38.00, z=211.48], EntityItem['item.item.seeds'/184, l='MpServer', x=-108.31, y=63.00, z=213.64], EntityItem['item.item.seeds'/185, l='MpServer', x=-106.50, y=63.00, z=213.09], EntityItem['item.item.seeds'/186, l='MpServer', x=-103.10, y=62.00, z=213.23], EntityBat['Bat'/187, l='MpServer', x=-105.25, y=39.46, z=221.47], EntitySkeleton['Skeleton'/188, l='MpServer', x=-100.47, y=25.00, z=243.78], EntityBat['Bat'/201, l='MpServer', x=-87.75, y=35.10, z=228.49], EntityCow['Cow'/202, l='MpServer', x=-86.19, y=69.00, z=253.67], EntitySkeleton['Skeleton'/203, l='MpServer', x=-96.95, y=49.00, z=262.50], EntitySkeleton['Skeleton'/204, l='MpServer', x=-84.68, y=48.00, z=263.16], EntityEnderman['Enderman'/205, l='MpServer', x=-81.48, y=48.00, z=268.46], EntityCow['Cow'/216, l='MpServer', x=-78.47, y=69.00, z=271.20], EntityPlayerDummy['entity.PlayerDummy.name'/500, l='MpServer', x=-158.33, y=64.00, z=267.29]]
	Retry entities: 0 total; []
	Server brand: fml,forge,LiteLoader
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_151, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1177272136 bytes (1122 MB) / 2329796608 bytes (2221 MB) up to 6429081600 bytes (6131 MB)
	LiteLoader Brand: 1.12.2-SNAPSHOT-r4CC2BB0-b4-4
	LiteLoader Mods: 1 loaded mod(s)
          - Macro / Keybind Mod version 0.15.4
	LaunchWrapper: 35 active transformer(s)
          - Transformer: net.minecraftforge.fml.common.asm.transformers.PatchingTransformer
          - Transformer: optifine.OptiFineClassTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.BlamingTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.SideTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
          - Transformer: $wrapper.com.kamesuta.mc.signpic.asm.SignPictureTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.Proxy
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.AccessTransformer
          - Transformer: invtweaks.forge.asm.ITAccessTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ItemBlockTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ItemBlockSpecialTransformer
          - Transformer: $wrapper.invtweaks.forge.asm.ContainerTransformer
          - Transformer: $wrapper.net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
          - Transformer: $wrapper.net.malisis.core.util.chunkblock.ChunkBlockTransformer
          - Transformer: $wrapper.net.malisis.core.renderer.transformer.MalisisRendererTransformer
          - Transformer: $wrapper.net.malisis.core.renderer.icon.asm.TextureMapTransformer
          - Transformer: $wrapper.net.malisis.core.util.clientnotif.ClientNotifTransformer
          - Transformer: $wrapper.org.blockartistry.DynSurround.asm.Transformer
          - Transformer: $wrapper.com.tterrag.blur.BlurTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.Proxy
          - Transformer: net.minecraftforge.fml.common.asm.transformers.TerminalTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.Proxy
          - Transformer: com.mumfrey.liteloader.transformers.event.EventTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: net.eq2online.macros.input.InputHandlerInjector
          - Transformer: com.mumfrey.liteloader.transformers.event.json.ModEventInjectionTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.Proxy
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ModAPITransformer
	JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:MaxPermSize=256m -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.1.2555 Optifine OptiFine_1.12.2_HD_U_C6 29 mods loaded, 29 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID              | Version                  | Source                                      | Signature                                |
	|:--------- |:--------------- |:------------------------ |:------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft       | 1.12.2                   | minecraft.jar                               | None                                     |
	| UCHIJAAAA | mcp             | 9.42                     | minecraft.jar                               | None                                     |
	| UCHIJAAAA | FML             | 8.0.99.99                | forge-1.12.2-14.23.1.2555.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge           | 14.23.1.2555             | forge-1.12.2-14.23.1.2555.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | servertools     | v1.2                     | [1.12.2] ServerTools v1.2.jar               | None                                     |
	| UCHIJAAAA | securitycraft   | v1.8.3                   | [1.12.x] SecurityCraft v1.8.3.jar           | None                                     |
	| UCHIJAAAA | woodconverter   | v2.9.2                   | [1.12]WoodConverter v2.9.2.jar              | None                                     |
	| UCHIJAAAA | betterplacement | 1.0.0-1                  | BetterPlacement-1.0.0-1.jar                 | None                                     |
	| UCHIJAAAA | blur            | 1.0.4-14                 | Blur-1.0.4-14.jar                           | None                                     |
	| UCHIJAAAA | codechickenlib  | 3.1.1.289                | CodeChickenLib-1.12-3.1.1.289-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | dsurround       | 3.4.7.2                  | DynamicSurroundings-1.12.2-3.4.7.2.jar      | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| UCHIJAAAA | presets         | 3.4.7.2                  | DynamicSurroundings-1.12.2-3.4.7.2.jar      | None                                     |
	| UCHIJAAAA | fbp             | 2.3.5                    | FancyBlockParticles-1.12.x-2.3.5.jar        | None                                     |
	| UCHIJAAAA | globalxp        | v1.4                     | globalxp-1.12.x-v1.4.jar                    | None                                     |
	| UCHIJAAAA | gravestone      | 1.8.4                    | gravestone-1.8.4.jar                        | None                                     |
	| UCHIJAAAA | waila           | 1.8.22                   | Hwyla-1.8.22-B37_1.12.jar                   | None                                     |
	| UCHIJAAAA | ichunutil       | 7.0.2                    | iChunUtil-1.12.2-7.0.2.jar                  | None                                     |
	| UCHIJAAAA | inventorytweaks | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                    | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAA | itemscroller    | 0.11.0                   | itemscroller-1.12.0-0.11.0.jar              | None                                     |
	| UCHIJAAAA | jei             | 4.7.4.81                 | jei_1.12-4.7.4.81.jar                       | None                                     |
	| UCHIJAAAA | journeymap      | 1.12-5.4.9               | journeymap-1.12-5.4.9.jar                   | None                                     |
	| UCHIJAAAA | malisiscore     | 1.12-6.0.4               | malisiscore-1.12-6.0.4.jar                  | None                                     |
	| UCHIJAAAA | malisisdoors    | 1.12-7.0.4               | malisisdoors-1.12-7.0.4.jar                 | None                                     |
	| UCHIJAAAA | morpheus        | 1.12-3.3.2               | Morpheus-1.12-3.3.2.jar                     | None                                     |
	| UCHIJAAAA | portalgun       | 7.0.0                    | PortalGun-1.12.2-7.0.1.jar                  | None                                     |
	| UCHIJAAAA | realrender      | 1.0.1                    | realrender-1.0.1.jar                        | None                                     |
	| UCHIJAAAA | signpic         | 2.8.1                    | SignPicture-1.12-2.8.1-universal.jar        | None                                     |
	| UCHIJAAAA | sit             | v1.0                     | sit-1.12.x-v1.0.jar                         | None                                     |
	| UCHIJAAAA | wawla           | 2.5.246                  | Wawla-1.12.2-2.5.246.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
SignPictureCorePlugin (SignPicture-1.12-2.8.1-universal.jar)
  com.kamesuta.mc.signpic.asm.SignPictureTransformer
BlurPlugin (Blur-1.0.4-14.jar)
  com.tterrag.blur.BlurTransformer
MalisisCorePlugin (malisiscore-1.12-6.0.4.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.7.2.jar)
  org.blockartistry.DynSurround.asm.Transformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13506 Compatibility Profile Context 23.20.15007.1005' Renderer: 'Radeon (TM) RX 480 Graphics'
	Launched Version: 1.12.2-forge1.12.2-14.23.1.2555
	LWJGL: 2.9.4
	OpenGL: Radeon (TM) RX 480 Graphics GL version 4.5.13506 Compatibility Profile Context 23.20.15007.1005, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge,LiteLoader'
	Type: Client (map_client.txt)
	Resource Packs: PureBDcraft 128x MC112.zip, Lively Default EDIT.zip, No underwater.png.zip, New Font - Fix.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_C6
	Render Distance Chunks: 20
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13506 Compatibility Profile Context 23.20.15007.1005
	OpenGlRenderer: Radeon (TM) RX 480 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 8
</details>

**Comment by TominoCZ** [comment]
Um.. You're trying to cast a block to your block right? Why not check if it is an instance of your block before you actually cast it?

**Comment by bl4ckscor3** [comment]
But why does the crash happen in the first place? I registered the stack provider to the XP Block, not to your FBPAnimationDummyBlock, hence the code shouldn't be executed in the first place.

**Comment by TominoCZ** [comment]
You're registering it to the block the player is looking at right?

**Comment by TominoCZ** [comment]
What my mod does is that whenever the player places the block, it is instantly set to my dummy ghost block so that you can't see the actual block(it is registered and placed only clientside). Then, after the animation is done, it 'places' the block into the world. (The block is there the whole time since I place my blocky only clientside - the block would appear if you right-clicked it)

**Comment by bl4ckscor3** [comment]
I'm registering the provider a specific block class (in this case XPBlock.class, see [here](https://github.com/bl4ckscor3/GlobalXP/blob/master/src/main/java/bl4ckscor3/mod/globalxp/imc/waila/WailaDataProvider.java#L24)). Maybe WAILA doesn't like that there is a discrepancy between client and server?

**Comment by TominoCZ** [comment]
I mean yeah what I'm doing is basically abusing an imperfection of the game to make the feature possible :D

It says it crashes at line 55 in your code. You can fix it by adding a check that the block you're casting is in fact an instance of your XPBlock.

**Comment by bl4ckscor3** [comment]
I'll just do that then, easier than tracking down why WAILA thinks that your block is my block :P
