### ISSUE TITLE
[Request] Block breaking particle configurations, per-block

### ISSUE THREAD

**Issue by VMan-2002** [TominoCZ/FancyBlockParticles#45]
Different blocks could have different particle rules, or use the existing config as a fallback if it doesn't have it's own. Maybe ore dictionary respecting too.

For example: leaves could be lighter, anvil could be heavier, etc.

**Comment by TominoCZ** [comment]
That's actually a pretty interesting idea. I could make this automatic using the value of the block's hardness.. Though gold would not have a correct weight..
