### ISSUE TITLE
Fancy Smoke & Fire Lighting

### ISSUE THREAD

**Issue by DarianLStephens** [TominoCZ/FancyBlockParticles#49]
## What went wrong:
Fancy Smoke and Light particles ignore all light besides sky
## What was expected:
Well, for them to respond to block light as well! It's weird having the particles be pitch-black when they are literally coming from a torch. Unless they're outside, then all is good.
## Steps to reproduce issue:
Load 1.7.10, install this mod, place a torch in an area with little-to-no skylight, observe the black hole torn in the universe.
## MC Version:
1.7.10
## FBP Version:
2.3.6
## Forge Version (e.g. 14.23.1.2604):
10.13.4.1614

It looks weird.
![2018-02-03_21 09 28](https://user-images.githubusercontent.com/15375876/35766188-38195710-0927-11e8-976f-16f7ce0ad36f.png)

**Comment by TominoCZ** [comment]
You're right.. that is weird.. I'll fix it as soon as I can.

**Comment by TominoCZ** [comment]
Will be fixed in version 2.3.7 ;)

**Comment by DarianLStephens** [comment]
That's good news. Are you also aware of entity collision not working? I'm not sure if it's because I updated from an old version of the mod, but I'm definitely not pushing particles out of my way anymore.
