### ISSUE TITLE
Crash right after jumping into water.

### ISSUE THREAD

**Issue by Boyownik** [TominoCZ/FancyBlockParticles#5]
When i jump into water it causes me crash. MC 1.10.2 When i spawn under water, everything is ok until i get up to breathe, i hear splash sound and right after crash. 

Okay i have found a reason, i guess... I've deleted Optifine and it's working fine. Maybe some of my Optifine options causes crash, i will try to find it.
Crash log: https://pastebin.com/pXv1YcNT

**Comment by Boyownik** [comment]
Well, even default options causes crash. So it's Optifine fault. I'am using Optifine_1.10.2_HD_U_D7.

**Comment by TominoCZ** [comment]
Add me on discord, I think we can make it work with optifine :)

**Comment by Boyownik** [comment]
Can you give me Your's digit tag number? I can't find You by only name :/

**Comment by TominoCZ** [comment]
#4919

**Comment by TominoCZ** [comment]
I will let this Issue open for now.
I've just released a new version of the mod. See if it works now :)
