### ISSUE TITLE
[Feature Request] Particle Physics

### ISSUE THREAD

**Issue by Eddi2015** [TominoCZ/FancyBlockParticles#52]
I thought about particle physics.
Particles should swim on water if they are wooden but if they aren't they should sink normally.
Apart from that I think the particles sink too fast. Would be cool if you'd change that.

**Comment by TominoCZ** [comment]
They sink neither too fast or too slow. They are just like the regular 2D digging particles but 3D.

I made them sink slower under water and wood particles float on water.
[screenshot](https://s18.postimg.org/5cevd88qv/2018-03-04_14.34.05.png)

Will be featured in the next version :)
