### ISSUE TITLE
Entity Collision

### ISSUE THREAD

**Issue by DarianLStephens** [TominoCZ/FancyBlockParticles#55]
## What went wrong:
Particles don't get pushed around by entities anymore, even with the 'Entity Collision' box checked.
## What was expected:
That the particles would be pushed out of the way by entities when I check the 'Entity Collision' box.
It's a small thing, but it's pretty nice while mining with a higher particle despawn time.
## Steps to reproduce issue:
1. Install the mod.
2. Tick the 'Entity Collision' box in the settings menu.
3. Watch as particles totally disregard your presence.
## MC Version:
1.7.10
## FBP Version:
2.3.7
## Forge Version (e.g. 14.23.1.2604):
10.13.4.1614

Thanks for fixing the fire particles, by the way. Also, it's great that water doesn't render over them anymore; that was the most subtly-annoying thing in Minecraft since they changed rendering.

**Comment by TominoCZ** [comment]
will be fixed in the upcoming version :)
