### ISSUE TITLE
Redstone Blocks don't work

### ISSUE THREAD

**Issue by RacerN2O** [TominoCZ/FancyBlockParticles#56]
## What went wrong:
Redstone blocks don't drop any paticles.

## What was expected:
Expected them to drop 3D Particles.

## Steps to reproduce issue:
Place a Redstone block and then destroy it.

## MC Version:
1.12.2

## FBP Version:
2.3.7

## Forge Version (e.g. 14.23.1.2604):
14.23.1.2555

**Comment by RacerN2O** [comment]
Nevermind, I found a setting for them. Didn't expect that exception, especially as a default.

**Comment by Eddi2015** [comment]
If you want an explanation: think of those redstone command block clocks ( those that use /fill command)
it would lag too much! that's why that exception was invented.
