### ISSUE TITLE
[1.8.9] Chests have invalid particles

### ISSUE THREAD

**Issue by Eddi2015** [TominoCZ/FancyBlockParticles#58]
## What went wrong:
 when trying to mine a chest those purple-black particles textures pop up (I do not mean the particles after the chest dropped)
## What was expected:
normal wooden particles
## Steps to reproduce issue:
mine a chest in survival
## MC Version:
1.8.9
## FBP Version:
2.3.8
## Forge Version (e.g. 14.23.1.2604):
2318 one

**Comment by TominoCZ** [comment]
will be fixed in the next update :)
