### ISSUE TITLE
[1.8.9] signs do not have any particles when mining them

### ISSUE THREAD

**Issue by Eddi2015** [TominoCZ/FancyBlockParticles#59]
## What went wrong:
as the title says (I mean the same particles as in the issue with the chest)
## What was expected:
notmal particles
## Steps to reproduce issue:
mine a sign in survival mode
## MC Version:
1.8.9
## FBP Version:
2.3.8
## Forge Version (e.g. 14.23.1.2604):
2318

**Comment by TominoCZ** [comment]
Signs seem to not have any digging particles in the first place.

**Comment by Eddi2015** [comment]
Is it possible to provide an option for that?
