### ISSUE TITLE
The game crashed whilst rendering particle

### ISSUE THREAD

**Issue by SextupleTap** [TominoCZ/FancyBlockParticles#61]
## What went wrong:

Game crashes whilst rendering particle, occurred in every new world I made, and outputs this error:

The game crashed whilst rendering particle
Error: java.lang.NoClassDefFoundError: com/sun/javafx/geom/Vec2f

I don't know if this will help but here are also my JVM arguments:
-Xmx4G -Xms1G -Xmn512m

I also tested the mod on its own to see if it conflicts with other mods but nope, it occurs on its own and with other mods.

(On both Survival Multiplayer and Singleplayer)

(Extra edit: I also completely reset my assets and libraries folder and reinstalled forge for 1.8.9 and the problem still persists)

(If needed I can also provide the full crash log)

## What was expected:

Crashing from a mod conflict or something along those lines, not instantaneous crashing when in a world.

## Steps to reproduce issue:

Occurs on ever new world made after a few seconds, I even turned off all my video settings but nothing worked.

"I place a torch down and it crashed, maybe smoke particles crash the game?"

## MC Version:

1.8.9

## FBP Version:

2.3.8

## Forge Version (e.g. 2604):

Recommended Version:
1.8.9 - 11.15.1.1722

**Comment by TominoCZ** [comment]
Yes, this problem has been reported already. I will leave this open so the others know it's been reported :)

**Comment by SextupleTap** [comment]
Alright got it :D 

(Despite this minor problem I still love the mod and will be waiting for the bugfix update :D!! Lol)

**Comment by TominoCZ** [comment]
I'm about to upload the new version ;)
