### ISSUE TITLE
[Request] - [Spawn Attack Particles] - [Setting]

### ISSUE THREAD

**Issue by SextupleTap** [TominoCZ/FancyBlockParticles#63]
## Request:

The request is similar to the "Spawn Redstone Particles" option.

It would be pretty cool if there was an option for "Spawn Attack Particles," where it will spawn small little fancy redstone particles to resemble blood when attacking any player, monster, or animal entities, they would be about the same size as the particles trailing behind the player when sprinting, maybe slightly bigger or smaller.

**Comment by TominoCZ** [comment]
I know it would look cool and stuff, but Fancy Block Particles only replaces vanilla **block** particles with 3D ones.

If I added this, it would no longer be Fancy **Block** Particles :/

**Comment by SextupleTap** [comment]
I understand what you mean... However, what ever happened with the rain and snow particles?
