### ISSUE TITLE
support for particles on mobs

### ISSUE THREAD

**Issue by Eddi2015** [TominoCZ/FancyBlockParticles#64]
wait... before you tell me that this mod is called fancy**Block**Particles not fancy**Mob**Particles,
I want to tell you that FBP already supports one mob: blazes!

Well my intetion is to add suport for endermans. Imagine purple cubes flying around the enderman.
And you could add support for that blood effect with redstone particles (the idea is from that other guy).

**Comment by TominoCZ** [comment]
The reason the mod 'supports' blazes is because the mod replaces fire and smoke particles.
I might make another mod that will make all the other particles 3D in the future.
