### ISSUE TITLE
Redstone block bug

### ISSUE THREAD

**Issue by Obsequies** [TominoCZ/FancyBlockParticles#77]

**Comment by TominoCZ** [comment]
Yes. That is a feature enabled by default and there is a good reason for it.
You know the command block/redstone block clock right? That ammount of particles would kill your CPU.

You can disable this feature in the FBP menu which you can open by pressing 'P' (as shown on the mod page).

**Comment by Obsequies** [comment]
Oh, nvm, I changed it in a config.
