### ISSUE TITLE
Water flickers different colors with BOP installed

### ISSUE THREAD

**Issue by TheQKnight** [TominoCZ/FancyBlockParticles#78]
## Steps to reproduce issue:
Install Biomes o' plenty and go to a colored ocean, then fly up and down until water changes to the vanilla color and back again.

## MC Version:
1.12.2

## FBP Version:
Affects versions 2.3.7 - 2.4.0

## Forge Version (e.g. 2604):
2655

**Comment by TominoCZ** [comment]
Are you sure this is caused by my mod?

**Comment by TheQKnight** [comment]
Oh, it seems to be happening with Galacticraft and this mod installed at the same time, not BOP, sorry.

**Comment by TheQKnight** [comment]
version 169 and higher it happens with

**Comment by TominoCZ** [comment]
Wait.. now I'm confused... Could you describe the issue in more detail please?

**Comment by TheQKnight** [comment]
Galacticraft, in the newer updates, changes the water color to a darker color. With this mod installed, water flickers between the new color one added by Galacticraft and the vanilla default one.

**Comment by TominoCZ** [comment]
I can't seem to find any dark water with Galacticraft. Could you give me some seed for the world so I know where to look please?

**Comment by TominoCZ** [comment]
I've looked at the differences in the code between 2.3.6 and 2.3.7 and I am sure that the next update will fix this :)

**Comment by TominoCZ** [comment]
Let me know in case this problem persists.
