### ISSUE TITLE
Crash when FBP is enabled in Twilight Forest

### ISSUE THREAD

**Issue by crashmaker18** [TominoCZ/FancyBlockParticles#82]
## Steps to reproduce issue:
Enable FBP and go into/load world where you are in the Twilight Forest.
When entering the world and going into the pause screen you can load the terrain without a problem but after you resume the game it disconnects you after a few seconds. The odd thing is the only particles there seems to be the portal's particles so I tried going to the overworld, boot up again with the mod enabled and I didn't get dc'd. I went through the portal again and in 2 seconds I was dc'd.
[Here](https://puu.sh/Ak9Us/d7024e0692.png) is the full mod list incase you think it's a confliction with anything else.

## MC Version:
1.7.10

## FBP Version:
2.4.0

## Forge Version (e.g. 2604):
10.13.4.1614

**Comment by TominoCZ** [comment]
Upload the crash log please

**Comment by crashmaker18** [comment]
Sorry, forgot about that.
https://pastebin.com/pPhRN8De
The highlighted text at line 2819 is where concluded the source.

**Comment by TominoCZ** [comment]
You didn't have to send the complete log file.. there is a crashlog file made to specifically show only the part where it crashed, but thanks. 

Anywas.. This looks like a problem with TwilightForest itself. Post this issue on TwilightForest's github issue page and add a link to the issue you posted here please.

https://github.com/TeamTwilight/twilightforest/issues

**Comment by crashmaker18** [comment]
Alright, thanks!

**Comment by TominoCZ** [comment]
I assume this is not getting fixed.
