### ISSUE TITLE
[Issue] Scala Import/Usage

### ISSUE THREAD

**Issue by artdude543** [TominoCZ/FancyBlockParticles#83]
Linked Issue: https://github.com/DarkPacks/SevTech-Ages/issues/2331
See: https://gist.github.com/artdude543/cf6fc74718c99a010dfacd04d822975d

This is caused on load as some clients do not require the complete Scala package. Side note why are you using `Path` from Scala? When you can use the standard `File` system from Java itself? Which does the same job and does not require another lib for usage?

## MC Version:
1.12.2
## FBP Version:
2.4.0
## Forge Version (e.g. 2604):
2680

**Comment by TominoCZ** [comment]
I thought I already removed all scala usages a while ago. I'll fix that.
The strange ting is that you seem to be the only one having this issue out of all the people playing the modpacks so far..

**Comment by artdude543** [comment]
Well I have 14 people from SevTech issues with said issue. (I dev the pack so I forwarded this on to you)

**Comment by artdude543** [comment]
https://github.com/TominoCZ/FancyBlockParticles/blob/74e25b58f826598524917de62432c5f001f53678/src_1.12.x/main/java/com/TominoCZ/FBP/handler/FBPConfigHandler.java#L16-L28

The fix you did makes the entire mod crash now. You need to update where you called it..

**Comment by TominoCZ** [comment]
I didn't have time to work on it and so I edited it from github. The IDE will tell me if there are any errors once I have time to work on it.

**Comment by justinrusso** [comment]
Any update on this?

**Comment by TominoCZ** [comment]
Yes, this will be fixed in version 2.4.1.
