### ISSUE TITLE
Biomes O' Plenty Grasses Have Grey Particles

### ISSUE THREAD

**Issue by SextupleTap** [TominoCZ/FancyBlockParticles#86]
## Steps to reproduce issue:

Install a mod(s) that add custom grass blocks (e.g. Biomes O' Plenty)

## MC Version:

1.12.2

## FBP Version:

FBP-2.4.0

## Forge Version (e.g. 2604):

Recommended Version: 1.12.2 - 14.23.3.2655

## Video Demonstration:

https://www.youtube.com/watch?v=rmXg5th6QgQ&feature=youtu.be

**Comment by TominoCZ** [comment]
Strange.... but then again, vanilla particles would be grey too...

**Comment by SextupleTap** [comment]
Well I mean... The vanilla particles have biome colors assigned to them properly, would the same/similar thing have to be done for modded grass blocks that use biome colors?

**Comment by TominoCZ** [comment]
Edited the title of this issue since it's not true. Aether's grass block works just fine with FBP.

This issue happens most likely due to the way the grasses in Biomes O' Plenty are programmed.

**Comment by TominoCZ** [comment]
This will be fixed in version 2.4.1.
