### ISSUE TITLE
[1.7.10]Game crashed when loading map

### ISSUE THREAD

**Issue by FuYang001** [TominoCZ/FancyBlockParticles#87]
## Steps to reproduce issue:
Game crashed when I was walking, with using weather2 and optifine shaders.
Crash report:https://pastebin.com/Suemvxjr
## MC Version:
1.7.10
## FBP Version:
2.4.0
## Forge Version (e.g. 2604):
1.7.10-Forge10.13.4.1614-1.7.10

**Comment by TominoCZ** [comment]
I'm not sure if the next update fixes the issue, but I hope so.
In case it doesn't, I'll leave this issue open.
