### ISSUE TITLE
Weird frozen Particles when breaking

### ISSUE THREAD

**Issue by H3roDude** [TominoCZ/FancyBlockParticles#91]
What is broken: When i break a block (no matter wich) the particle froze and floading in the air right after breaking. After some time the particles are falling on the Ground and everythin kworks fine till i move 5-8 blocks further and start breaking again

MC Version: 1.12.2

 FBP Version: 1.12.x-2.4.0

 Forge Version: 2707

**Comment by TominoCZ** [comment]
Are you sure you didn't toggle Freeze Mode by accident?

**Comment by H3roDude** [comment]
i wasnt aware this mode exist :P Thank you!
