### ISSUE TITLE
FBP and SmartHUD's Item Pickup

### ISSUE THREAD

**Issue by Drag0nsaver** [TominoCZ/FancyBlockParticles#94]
If you have FBP and SmartHUD installed at the same time, the item pickup readout from SmartHUD will not show. When you toggle FBP off through the in game options, SmartHUD's item pickup readout is visible once more.

## Steps to reproduce issue:
Only need Fancy Block particles and SmartHUD installed. If Fancy Block Particles are enabled, the item pickup readout which would be in the lower left is just gone. Disabling Fancy Block Particles will return visibility of the Item Pickup.

## Forge Version (e.g. 2604): 14.23.4.2729

I have also submitted this information to SmartHUD's issue tracker [https://github.com/SleeplessDevelopment/SmartHUD/issues/19](https://github.com/SleeplessDevelopment/SmartHUD/issues/19)

**Comment by TominoCZ** [comment]
Yes.. I think I know exactly why this is happening... I once released an update which was meant to optimize the rendering of the particles but it instead brought in more problems than expected. 

Welp, I will have to rewrite a lot of the code anyway.. I will start working on the mod again soon, I was really busy and so I had to take a break.

**Comment by TominoCZ** [comment]
This will be fixed in version 2.4.1.
