### ISSUE TITLE
[Feature Request] Higher/Lower Gravity

### ISSUE THREAD

**Issue by LemonHeadOnGit** [TominoCZ/FancyBlockParticles#96]
I would like to request a feature implemented into the mod:
The ability to have higher or lower gravities.

The reason for this is because I use this mod with Galacticraft a lot, and I have a space station which is Zero Gravity, and even if i turn the gravity to 0.5, it doesn't have the same effect. I don't expect NO gravity but i would like at least 0.05 - 0.1 gravity.

Thanks.

P.S. If this has already been requested, i'm sorry. Also this mod is amaze.

[EDIT]: Also some planets have high gravity so maybe you could push it up to 2.5 maybe 3.0

**Comment by DarianLStephens** [comment]
Y'know, separate setting for different dimensions would be a very welcome addition. It would allow setting a specific gravity for different planets, let Dynamic Surroundings' Nether storm stuff work...
If feasible, I think it could be a great feature.

**Comment by TominoCZ** [comment]
Making different gravity seetings for each dimension would a little overkill... xd

**Comment by DarianLStephens** [comment]
Not just gravity, but the entire config able to be set on a per-dimension basis.
That way, if any of the effects interfere with something in the dimension (Such as Dynamic Surroundings and its Nether Weather), or would work better tweaked (Like a space dimension with lower gravity), you'd be able to do it easily.
