### ISSUE TITLE
[Feature Request] Remove config restrictions & other things

### ISSUE THREAD

**Issue by ViciousVinnyD** [TominoCZ/FancyBlockParticles#97]
If you try increasing the particle limit past 5^3 the mod will automatically set it back to 5^3. I want more particles, so it would be nice if this was removed.

Also, I would like the option to disable random scaling. And the smooth transitions config option doesn't actually disable the smooth transitions.

**Comment by TominoCZ** [comment]
Too many particles will kill your CPU and GPU, also if we keep going like 6^3, 7^3, the ammounts of particles would be 216 and 343 **for one destroyed block**.
You should be able to disable the random scaling. I'll look more into it.
Strange.. Well I'll be removing the smooth transition option as it doesn't help and is really just inconvenient.

**Comment by TominoCZ** [comment]
Yes, the smooth transitions will be enabled by default.

**Comment by ViciousVinnyD** [comment]
Perhaps double the default (8^3), that seems to be the safe upper limit for my GPU. The reason I wanted a high upper limit is because I wanted to simulate a block breaking into it's individual pixels by using a combination of cartoon mode, small particle size and a large particle number.

**Comment by TominoCZ** [comment]
Oh I see.. Well the thing is that the particles don't have the pixel color at that position of the texture...
The particle texture is random, so it won't look anything like the original block.
It would be really hard to implement so I don't think that's happening.

I'll raise the upper particle limit then :D

**Comment by ViciousVinnyD** [comment]
I know, that doesn't matter though. The block breaking into individual pixels is more than enough.

**Comment by SextupleTap** [comment]
I just want to ask how the block turning into individual pixels concept would even work.

Would the mods rely on the resource pack, analyzing every single image file and relating it to a in game block to determine the pixel area of the image, and then cube that to get the pixel count of every single individual block, also extending further into analyzing the model files for blocks with geometry more complex then just being a 16 by 16 by 16 cube, (such as an anvil, or a crop that has textures converge at cross sections)?

If so, that process sounds resource intensive (I don't know if it actually is it just sounds like it).

And if what I described above is a completely fictional process, then please inform me on how it would work then, as I am very curious :)

Also just 16 by 16 by 16 cube alone produces 4,096 pixel particles per block...

An alternative would be to use the surface area of a block(s), but in a 16 by 16 by 16 cube that produces 1,536 pixels per block, which is still a tone of pixel particles.

**Comment by TominoCZ** [comment]
I 100% agree with @SextupleTap

**Comment by ViciousVinnyD** [comment]
@SextupleTap What you just described is indeed fictional. You simply use cartoon mode and small particle scale and each particle colors itself using a random pixel from the texture instead of using a random portion of the texure like it normally does. Yes, it creates 4096 particles, which is silly. A hollow square does indeed make this much more manageable, and would actually be quite nice to have.

Also this whole idea was just a concept I wanted to test but I was unable to because of the hardcoded restrictions, which I really don't like having. The in-game GUI limits the range anyway, so only advanced config users are actually able to set it to out of range values.

**Comment by TominoCZ** [comment]
The only way you could set it higher is by going into the memory of Minecraft using CheatEngine and chaning the right variable xD

**Comment by TominoCZ** [comment]
Yeah.. I think I can disable the config restrictions when you reload the config file ;)

**Comment by ViciousVinnyD** [comment]
@TominoCZ Yeah that would be great thanks. Limit the gui to prevent kids breaking their game, and remove it in configs so nerds can flex their graphics cards.

**Comment by teak1** [comment]
was that limit ever removed? and if so from what versions?

**Comment by TominoCZ** [comment]
The restrictions will be removed in version 2.4.1. I've been busy and I began working on FBP again earlier today. The new version will be released soon.

**Comment by TominoCZ** [comment]
xD
![unlimited_scale](https://user-images.githubusercontent.com/24359011/47384635-1e212900-d708-11e8-9d73-ac3eb869a4fb.gif)
